os: osx
language: generic
env: PYTHON_INSTALLER=brew

install:
  - python --version
  - pip install PyYAML argparse rospkg vcstools catkin_pkg python-dateutil rosdistro
  - pip install nose coverage flake8 mock codecov
  - which nosetests
  - nosetests
